
export const CHANGE_ENTER_LOADING = "video/CHANGE_ENTER_LOADING";
export const CHANGE_WHETHER_LOADING = "video/CHANGE_WHETHER_LOADING";
export const CHANGE_STILL_LOADING = "video/CHANGE_STILL_LOADING";
export const SET_CURRENT_MUSIC_VIDEO = "video/SET_CURRENT_MUSIC_VIDEO";
export const SET_CURRENT_MUSIC_VIDEO_PLAY = "video/SET_CURRENT_MUSIC_VIDEO_PLAY";
export const SET_CURRENT_MUSIC_VIDEO_INFO = "video/SET_CURRENT_MUSIC_VIDEO_INFO";
export const SET_CURRENT_SIMILAR_MUSIC_VIDEO = "video/SET_CURRENT_SIMILAR_MUSIC_VIDEO";
export const SET_CURRENT_MUSIC_VIDEO_COMMENT = "video/SET_CURRENT_MUSIC_VIDEO_COMMENT";
