export const CHANGE_ARTIST = 'singer/CHANGE_ARTIST';
export const CHANGE_SONGS_OF_ARTIST = 'singer/CHANGE_SONGS_OF_ARTIST';
export const CHANGE_ENTER_LOADING = 'singer/CHNAGE_ENTER_LOADING';
export const CHANGE_ARTIST_INFO = 'singer/CHANGE_ARTIST_INFO';
export const CHANGE_ARTIST_ALBUM = 'singer/CHANGE_ARTIST_ALBUM';
export const CHANGE_ARTIST_MUSICVIDOE = 'singer/CHANGE_ARTIST_MUSICVIDOE';
